# Go!
language: go
go:
  - 1.11.3

# Disable annoying emails.
notifications:
  email: false

# Make sure to install the dependencies.
install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

# Run the actual tests.
script: make test
