---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang}

inputs:
- name: bugtracker-server

outputs:
- name: bin

run:
  path: go
  args: [test]
  dir: ./bugtracker-server
